### ISSUE TITLE
Size limit of Seurat object to convert to Anndata

### ISSUE THREAD

**Issue by levinhein** [cellgeni/sceasy#15]
Hello! Does sceasy have size limit for converting Seurat objects to Anndata format?

When I convert a 8GB Seurat object it was successful and quick. But when I try to process 10GB Seurat object, it processes for a long time (~20minutes) and always crashes my R/Rstudio run, which I tried many times. Thank you!

**Comment by nh3** [comment]
`sceasy` itself has no size limit. The difference you see might have something to do your object or computation environment.
