### ISSUE TITLE
Transformation from AnnData/Loom produces SCE object that R doesn't seem to like

### ISSUE THREAD

**Issue by pcm32** [cellgeni/sceasy#17]
Input dataset: https://humancellatlas.usegalaxy.eu/datasets/11ac94870d0bb33a4d823102dcb034bc/display?to_ext=loom

Result dataset was specifically https://humancellatlas.usegalaxy.eu/datasets/11ac94870d0bb33a005bfb8cba4fb8dd/display?to_ext=rdata (although it is an RDS, long story).

Entire history here:
https://humancellatlas.usegalaxy.eu/u/pmoreno/h/atlas-scanpy-scmap-e-geod-94641-2

Will add more details on the R part.

**Comment by a-solovyev12** [comment]
Parsing the object in R via `readRDS()` and then getting its attributes causes the following: 
```
> query_sce
class: SingleCellExperiment 
dim: 
metadata(5): neighbors pca raw.var raw.X louvain
Error in getClass(element.type) : “SimpleAssays” is not a defined class
```

**Comment by nh3** [comment]
hmm, I am having the same error querying the content of your rds file. However, https://humancellatlas.usegalaxy.eu/datasets/11ac94870d0bb33a005bfb8cba4fb8dd/stdout seems to suggest the rds is normal under `sceasy_convert`'s container environment. I also tried running the conversion code in my local environment using the input loom and I can read normally the content of the converted rds in the same environment. My guess is that the bioconductor/SingleCellExperiment versions are different/incompatible between `sceasy_convert` and `scmap_preprocess_sce`.
