### ISSUE TITLE
Selecting assay type to convert in SCeasy 

### ISSUE THREAD

**Issue by RolantusdataExp** [cellgeni/sceasy#23]
Hi, 
Really enjoy this package! Way easier than other solutions. 
I have run into the issue that when I convert from seurat -> anndata it only takes my RNA assay (assay = RNA), but I would prefer to convert my SCTransformed assay instead. I can't find a way to do this in your vignette. 

Best regards, 
Peter 
University of Southern Denmark

**Comment by ShanSabri** [comment]
I'm also interested on this topic. Also is it possible to include the Raw counts when converting Seurat --> AnnData?

**Comment by nh3** [comment]
You could try passing `assay=<assay_name>` to the function. By default, `<assay_name>` is set to `"RNA"`.

**Comment by RolantusdataExp** [comment]
Thanks for the reply, @nh3.

**Comment by ShanSabri** [comment]
@nh3 How about slot? Like what if I wanted to export the raw RNA counts in the anndata object?

**Comment by nh3** [comment]
> @nh3 How about slot? Like what if I wanted to export the raw RNA counts in the anndata object?

You could pass `main_layer="counts"`.
