### ISSUE TITLE
error converting loom to sce

### ISSUE THREAD

**Issue by akhst7** [cellgeni/sceasy#24]
Hi, 

When converting a loom file to sce as follows, I got the following error. 

```
> convertFormat("skin.loom", from = "loom", to = "sce", outFile = "skin.rds" )
Error in readExchangeableLoom(inFile, backed = FALSE, main_layer_name = main_layer_name,  : 
  file.exists(filename) is not TRUE
```
Any help will be appreciated.

**Comment by nh3** [comment]
Given the error message, it seems "skin.loom" doesn't exist in your working directory.

**Comment by nh3** [comment]
Closing for now. Please re-open if it's not related to file existence.

**Comment by Vinayaksiv-17** [comment]
I have the same issue. But it is not related to file existence.

**Comment by akhst7** [comment]
@Vinayaksiv-17, post the error message.

**Comment by Vinayaksiv-17** [comment]
It's the exact same error
> convertFormat("skin.loom", from = "loom", to = "sce", outFile = "skin.rds" )
Error in readExchangeableLoom(inFile, backed = FALSE, main_layer_name = main_layer_name,  : 
  file.exists(filename) is not TRUE

**Comment by Vinayaksiv-17** [comment]
I solved it. It was a typo
