### ISSUE TITLE
Default conda installation instructions for searat -> h5ad convert not working

### ISSUE THREAD

**Issue by inodb** [cellgeni/sceasy#30]
On OSX it took a bit of trial & error to get the environment of sceasy working.
 
 I used mamba over conda because it is faster, but should result in the same env: 

 ```
 mamba create -n sceasy r-sceasy python=3
 ```
 Some deps were not installed properly, so had to reinstall `openblas` and `r-stringi`:
 ```
 conda install anndata==0.6.19 -c bioconda
 mamba install -c conda-forge openblas
 mamba remove r-stringi
 mamba install r-stringi r-sceasy
 ```
 Then there is some funkiness with [anndata not working with the scipy env](https://github.com/theislab/scanpy/issues/643#issuecomment-494058404):
 ``` 
 pip install scipy==1.2.1
 ```

After that things worked fine. Maybe adding some of these notes to the README could be helpful. That being said: compared to most bioinf tools this was pretty easy to install, so kudos 👏

**Comment by nh3** [comment]
Many thanks for your suggestion! Readme updated.
