### ISSUE TITLE
The big issue about converting h5ad into seurat rds 

### ISSUE THREAD

**Issue by honghh2018** [cellgeni/sceasy#49]
Hi Developers,
     I encounter issue that it was go wrong when running the Seurat NormalizeData in the object through the h5ad convert into seurat rds 
     The error lying below:
     Calls: NormalizeData ... NormalizeData.Seurat -> [[<- -> [[<- -> Key -> Key.Seurat -> vapply

Hope to update the sceasy to avoid this issue? i would sent this message to Seurat Lab to dig out what happen in it and solved hopefully it.

Best,
Hanhuihoing

**Comment by JarningGau** [comment]
set assay key can solve it.
seu@assays$RNA@key <- "rna_"

**Comment by nh3** [comment]
Thank you both! This is now addressed by #52.
