### ISSUE TITLE
Error when converting anndata to seurat

### ISSUE THREAD

**Issue by Merlin2333** [cellgeni/sceasy#56]
When I use the function `sceasy::convertFormat(seurat_object, from="seurat", to="anndata",outFile='filename.h5ad')`, an error occurs: `Error in validObject(.Object) : invalid class "DimReduc" object: invalid object for slot "cell.embeddings" in class "DimReduc": got class "data.frame", should be or extend class "matrix"`. 

It turns out that `_scvi_extra_categoricals` from the obsm field is data.frame rather than matrix (numpy). It would be greatly appreciated if the function can wraps/convert dataframs as matrix objects while reading them.

**Comment by Lila14** [comment]
I fixed the issue in a fork: https://github.com/elementgenomicsinc/sceasy

Also created a PR

**Comment by nh3** [comment]
Thank you @Merlin2333 for reporting the issue and @Lila14 for the fix.
