### ISSUE TITLE
Updating dependencies

### ISSUE THREAD

**Issue by errcricket** [cellgeni/sceasy#57]
Is there a chance that sceasy will be updated to use current versions of anndata and scipy? As of February 2022, the most recent version of of anndata is 0.9 and scipy is 1.8.

**Comment by nh3** [comment]
Thank you for raising this.

The requirements for specific versions of `anndata` and `scipy` in the README had been out-dated for a long while and has just been removed (with the newly released v0.0.7).

Actually, the package itself poses no restriction on anndata and scipy versions. If you install from source it should just install regardless of python package versions. The version requirements in the bioconda recipe will be removed with the new release.
