### ISSUE TITLE
error convert anndata to seurat

### ISSUE THREAD

**Issue by joyduck** [cellgeni/sceasy#65]
I got an error when converting anndata to seurat:

Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'as.matrix': 'match' requires vector arguments

it appears it has something to do with the obsm data in anndata, each of the obsm data is an array, one dimension as far as I can tell, maybe not be able to convert to a matrix?? Please advise how to fix it.

Thanks

**Comment by zhouzhendiao** [comment]
> adata <- sc$read_h5ad("xxx.h5ad") sceasy::convertFormat(adata, from="anndata", to="seurat", outFile='xxx.rds') I got an error like this, hope anyone can help me with this
> 
> Error in path.expand(inFile) : invalid 'path' argument

It require file path of adata rather than adata objet.
